vpc_name       = "dev-vpc"
public_subnet  = "dev-public-subnet"
private_subnet = "dev-private-subnet"
#internet_gateway="dev-igw"
#Nat_gateway="dev-nat-gw"
public_route_table  = "dev-public-rt"
private_route_table = "dev-private-rt"
