vpc_name    = "dev-vpc"
public_sn   = "dev-public-subnet"
private_sn  = "dev-private-subnet"
igw         = "dev-igw"
#Natgw       = "dev-nat-gw"
public_rtb  = "dev-public-rt"
private_rtb = "dev-private-rt"
